### ISSUE TITLE
İlk Kurulum, Beyaz Ekran

### ISSUE THREAD

**Issue by ikinciadam** [kahvedigital/iyzico-opencart#16]
Journal Tema kullanıyorum, dosyaları ftp ye aktardıktan sonra, eklentilerden modülün kurulumunu yapıyorum, sonrasında API key ve secret girişi ve Aktifleştirme için düzenleme ekranına ulaşmak istediğimde beyaz ekran alıyorum. Sürümüm 2.3.0.2, Journal Tema kullanıyorum

**Comment by kahvedigital** [comment]
Merhabalar,

Beyaz ekranda aldığınız hata kodunu iletirseniz yardımcı olabiliriz.
