### ISSUE TITLE
Ödeme ekranı, tekrarlayan refresh

### ISSUE THREAD

**Issue by ikinciadam** [kahvedigital/iyzico-opencart#17]
Journal Tema kullanıyorum, ödeme ekranı tek sayfada Journal kolay satın alma ekranı. Bu sayfada zaman zaman ödeme metodu olarak kredi kartı seçildiğinde, gelecek olan ödeme formu kendini yeniliyor, sonrasında bunu bir kaç kez tekrarlıyor. Sayfada herhangi boş bir yere tıklanınca da yine tekrarlıyor bu load işlemini. Sürümüm 2.3.0.2, Journal Tema kullanıyorum.

**Comment by kahvedigital** [comment]
Merhabalar modülümüz şuan tek sayfada ödeme desteklememektedir.

**Comment by egemenozkan** [comment]
Merhaba,
Bir sene içerisinde bu konuda herhangi bir çalışma olmadı mı ? İyzico'dan destek mi alamıyorsunuz ?

**Comment by kahvedigital** [comment]
Merhaba,
One page için geliştirme yapıyoruz yakında güncelleme yayımlayacağız.
